name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
